# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61e5f2447b0304b852e8f9cd28a0a540ac669e67af3c4b2b58809436fc5675c86d22bb84cbe4da95b9bd57022b75d1a52b4cbed43f44bbb8c8657ff14cd5546e

test:
  secret_key_base: 89b569810a542394654224c6f9c516e1699829f9b4403b8cff24183c389c2ad3cf28df95ab8f4815e118b933df89198787b7a83387577134884e96222bfe2d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
